package com.fireworks.myeventsdk.Utils

class PrefConstant {

    companion object {
        const val BASE_URL = "base_url"

        const val BASE_URL_LIVE = "base_url_live"
        const val BASE_URL_STAGING = "base_url_staging"

        const val NOTIFICATION = "notification"
        const val LANGUAGE = "language"
        const val USER_NAME = "user_name"
        const val USER_TITLE = "user_title"
        const val USER_FNAME = "user_firstname"
        const val USER_LNAME = "user_lastname"
        const val USER_EMAIL = "user_email"
        const val USER_PHONE = "user_phone"
        const val USER_COUNTRY_CODE = "user_country_code"
        const val USER_PIC = "user_pic"
        const val USER_NRIC = "user_nric"
        const val LOGGED_IN_STATUS = "login_status"
        const val SOCIAL_MEDIA_TYPE = "socialmediatype"
        const val SOCIAL_MEDIA_TOKEN = "socialmediatoken"
        const val PW_STR = "pw_str"
        const val PW_64 = "pw_64"
        const val USER_TOKEN = "user_token"
        const val REMEMBER_ME = "remember_me"
        const val SID = "sid"
        const val NEWS_ID = "news_id"
        const val NEWS_CAT = "news_cat"
        const val IMAGE_DETAILS = "main_image_details"
        const val CUSTOMER_ID = "customer_id"
        const val MERCHANT_ID = "merchant_id"
        const val CHANGE_PW = "change_pw"
        const val REGISTER = "register"
        const val URL = "url"
        const val DEVICE_TOKEN = "device_token"
        const val POINT = "point"
        const val COUPON_ID = "coupon_id"
        const val WALLET_ID = "wallet_id"
        const val EVENT_ID = "event_id"
        const val ITEM_ID = "item_id"
        const val ITEM_NAME = "item_name"
        const val ITEM_IMAGE = "item_image"
        const val QUANTITY = "quantity"
        const val REDEEM_POINT = "redeem_point"
        const val TYPE = "type"
        const val CUSTOMER_TYPE = "customer_type"
        const val STATUS = "status"
        const val DATE = "date"
        const val CONDITION = "condition"
        const val QR = "qr"
        const val POSITION = "position"
        const val DISPLAYED_MESSAGES = "displayed_message"
        const val IMAGE_URL = "image"
        const val TAB_POSITION = ""
        const val TRANS_ID = "tid"
        const val TRANS_REASON = "treason"
        const val TITLE = "title"
        const val SHOW_NOTIFICATION = "shownotification"
        const val NOTI_APP_PUSH = "noti_app_push"
        const val NOTI_GENERAL = "noti_general"
        const val NOTI_REWARD = "noti_reward"
        const val FLOOR_IMAGE = "floor_image"
        const val FIRST_TIME_LOADED = "not_fresh_installation"
        const val INVITATION = "false"
        const val INCOMPLETE_REGISTRATION = "incomplete_registration"
        const val WALLET_TAB = "wallet_tab"
        const val DIRECTORY_ID = "directory_id"
        const val NRIC_PASSPORT = "nric_passport"
        const val DISPLAY_NAME = "pref_name"
        const val REGISTER_GENDER = "register_gender"
        const val REGISTER_RESIDENCE = "register_residence"
        const val REGISTER_NATIONALITY = "register_nationality"
        const val REGISTER_RACE = "register_race"
        const val PROFILE_DOB = "profile_dob"
        const val REFERRAL_CODE = "referral_code"
        const val REFERRAL_URL = "referral_url"
        const val USER_REFERRAL = "user_referral"
        const val PROFILE_ADDRESSONE = "profile_addressone"
        const val PROFILE_ADDRESSTWO = "profile_addresstwo"
        const val PROFILE_CITY = "profile_city"
        const val PROFILE_STATE = "profile_state"
        const val PROFILE_POSTCODE = "profile_postcode"
        const val REWARD_IMAGE = "reward_image"
        const val REWARD_ID = "reward_id"
        const val REWARD_TITLE = "reward_title"
        const val REWARD_POINT = "reward_point"
        const val REWARD_DELIVERY = "reward_delivery"
        const val REWARD_ADDRESS = "reward_address"
        const val REWARD_ADDRESSONE = "reward_addressone"
        const val REWARD_ADDRESSTWO = "reward_addresstwo"
        const val REWARD_CITY = "reward_city"
        const val REWARD_STATE = "reward_state"
        const val REWARD_POSTCODE = "reward_postcode"
        const val DEFAULT_MALL = "default_mall"

        const val IS_MIGRATED = "is_migrated"
        const val MIGRATED_CARD_NO = "migrated_card_no"
        const val MIGRATED_FIRST_NAME = "migrated_first_name"
        const val MIGRATED_LAST_NAME = "migrated_last_name"
        const val MIGRATED_EMAIL = "migrated_email"
        const val MIGRATED_COUNTRYCODE = "migrated_countrycode"
        const val MIGRATED_PHONE = "migrated_phone"
        const val MIGRATED_NRIC = "migrated_nric"
        const val MIGRATED_BALANCE = "migrated_balance"

        const val MIGRATED_IDTYPE = "migrated_idtype"
        const val MIGRATED_ID = "migrated_id"
        const val MIGRATED_DOB = "migrated_dob"
        const val MIGRATED_GENDER = "migrated_gender"
        const val MIGRATED_RACE = "migrated_race"
        const val MIGRATED_ADDRESSONE = "migrated_addressone"
        const val MIGRATED_ADDRESSTWO = "migrated_addresstwo"
        const val MIGRATED_POSTCODE = "migrated_postcode"
        const val MIGRATED_CITY = "migrated_city"
        const val MIGRATED_STATE = "migrated_state"

        const val RESET_PASS_PHONE = "reset_phone"
        const val RESET_PASS_COUNTRY = "reset_country"
        const val IS_RESET_NEW_FLOW = "reset_by_sms"
        const val IS_RESET_BY_EMAIL = "reset_by_email"
    }
}