package digital.fireworks.kpdrm.data.dto.events_detail

data class Detail(
    val address: String,
    val bookmark_status: Int,
    val description: String?,
    val featured_image: String,
    val id: String,
    val label: String,
    val latitude: String,
    val limit_message: String,
    val longitude: String,
    val mall: Int,
    val merchantid: String,
    val more_details: String,
    val points: String,
    val purchase_end: String,
    val purchase_limit: String,
    val purchase_start: String,
    val quantity_message: String,
    val redeem_end: String,
    val redeem_start: String,
    val redeem_status: Int,
    val share_link: String,
    val stock_left: Any,
    val stock_message: String,
    val stock_status: Int,
    val title: String,
    val validity: String,
    val validity_message: String,
    val rank_text: String,
    val purchase_start_time: String,
    val interest: Boolean
)